### ISSUE TITLE
Найти и составить словарь английских слов

### ISSUE THREAD

**Issue by Orgyflame** [Orgyflame/Lab8-blind-printing#1]
Требования к словарю:
* Одна строка - одно слово
* Длина слов должна быть от 1 до 20
* Должны существовать слова длины 1 и 2
* Тем больше слов - тем лучше
* Файл dict-en.txt

**Comment by andrew-besedin** [comment]
https://github.com/Orgyflame/Lab8-blind-printing/commit/06faaaa7d28522a11bedf7e6a7eb5a814cfcb1cc
