### ISSUE TITLE
Генерация следующей строки

### ISSUE THREAD

**Issue by Orgyflame** [Orgyflame/Lab8-blind-printing#11]
```pascal
generateNextString(originalString, userString: string): string;
```

**Comment by Mathew-bal** [comment]
Ну, это не прям полная генерация новой строки. Скорее проверка и исправление в соответствии с правилами
*Ошибки исправлены

![Опи ПроверкаСтроки](https://user-images.githubusercontent.com/120332273/208997487-e5879390-f68f-4936-9cda-ad2796128c18.png)
