### ISSUE TITLE
Разработка интерфейса программы

### ISSUE THREAD

**Issue by Orgyflame** [Orgyflame/Lab8-blind-printing#15]
- [x] #7 
- [x] #8 
- [x] #9

**Comment by Orgyflame** [comment]
Общие требования:
1. При игровом процессе должен быть виден номер уровня, количество дупликатов в случае ошибки
2. После пользовательского ответа, поле должно очищаться(возможно за исключением хедера с данными из 1 пункта)

**Comment by Mathew-bal** [comment]
- Интерфейс он и в Африке интерфейс
- Поддержка двух языков
- Clean_screen находится здесь
- Принимаются любые предложения
- Бтв, case of для строк не работает(

  
![Интерфейс](https://user-images.githubusercontent.com/120332273/208517714-3d348176-fbcf-4fce-8974-df1f896459eb.png)
