### ISSUE TITLE
Найти и составит словарь русских слов

### ISSUE THREAD

**Issue by Orgyflame** [Orgyflame/Lab8-blind-printing#5]
Требования к словарю:

* Одна строка - одно слово
* Длина слов должна быть от 1 до 20
* Должны существовать слова длины 1 и 2
* Тем больше слов - тем лучше
* Файл dict-ru.txt

**Comment by antbesed** [comment]
https://github.com/Orgyflame/Lab8-blind-printing/commit/55d5c25fac51f261c4997d2f597d4c9a366b9939
