### ISSUE TITLE
Переход на новый уровень

### ISSUE THREAD

**Issue by Orgyflame** [Orgyflame/Lab8-blind-printing#9]
```pascal
writeNewLevel(level: integer)
```

**Comment by Orgyflame** [comment]
1. Очистка всего экрана
2. По центру надпись COMPLETE LEVEL {level}
3. Под надписью `Press ENTER to continue`

**Comment by Mathew-bal** [comment]
- Думаю, что имеет смысл передавать и duplicate_count, чтобы каждый раз заново его не считать
- Также добавил поддержку языка

![Переходнановыйуровень](https://user-images.githubusercontent.com/120332273/208516207-aa366e8e-5fa3-4d92-8174-49c39afcd751.png)
